project_id = "fuoefkfekhzhlsblloal"

[functions.google-oauth-handler]
verify_jwt = false

[functions.post-meta-tags]
verify_jwt = false

[functions.process-live-gift]
verify_jwt = true

[functions.upload-story-media]
verify_jwt = true

[functions.create-story]
verify_jwt = true

[functions.track-story-view]
verify_jwt = true

[functions.upload-live-thumbnail]
verify_jwt = true

[functions.delete-story]
verify_jwt = true